spring.application.name=config-service

server.port=9999
spring.cloud.config.server.git.uri=file:///C:/Users/DADAS/Desktop/Parallel-and-Distributed-Systems/micro-services-architecture-app/config-repo
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.skip-ssl-validation=true
