spring.application.name=kafka-spring-cloud-stream
server.port=8080
spring.cloud.stream.bindings.consumer-in-0.destination=t2
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=t3

spring.cloud.stream.bindings.kStreamFunction-in-0.destination=t3
spring.cloud.stream.bindings.kStreamFunction-out-0.destination=t4

spring.cloud.function.definition=consumer;pageEventSupplier;kStreamFunction

spring.cloud.stream.bindings.pageEventSupplier-out-0.producer.poller.fixed-delay=200
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000

